version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ../postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - 5432:5432
  # server:
  #   container_name: warehouse-server
  #   build:
  #     context: ../
  #     dockerfile: ./docker/server.dockerfile
  #   volumes:
  #     - ../:/usr/src/app
  #   depends_on:
  #     - db
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   command: "pnpm run start:dev"
